Vagrant.configure(2) do |config|

  # Ubuntu 14.04 is capable of running docker without any kernel modifications
  config.vm.box = "centos/7"

  config.vm.hostname = "centos-7-docker"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y install git docker ansible wget
    sudo yum clean all
  SHELL
end
