Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # Ubuntu 14.04 is capable of running docker without any kernel modifications
  config.vm.box = "cents-7-docker-ansible"

  ssh_public_key = File.read(File.join(Dir.home, ".ssh", "id_rsa.pub"))
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  #config.vm.network "private_network", ip: "192.168.56.222", auto_config: false
  #config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2

  config.vm.hostname = "openshift-origin-allinone-1"

  #設定上層可以在VM中看到
  config.vm.synced_folder "../", "/data"

  config.vm.provision "shell", inline: <<-SHELL
    echo "#{ssh_public_key}" >> /home/vagrant/.ssh/authorized_keys
    cd /opt
    #wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz
    rm -rf openshift-origin
    #cp /data/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz ./
    tar xvf /data/openshift-origin-server-v1.4.1-3f9807a-linux-64bit.tar.gz -C /opt
    mv openshift-origin* openshift-origin
  SHELL

  config.vm.provision :shell, :privileged => false, :run => 'always', inline: <<-SHELL
    sudo kill $(ps aux | grep 'sudo ./openshift' | awk '{print $2}')
    sudo service docker start
    cd /opt/openshift-origin
    export PATH="$(pwd)":$PATH
    #sudo ./openshift start --public-master=https://192.168.56.222:8443
    #sudo ./openshift start --public-master=https://10.0.2.15:8443
    nohup sudo ./openshift start --public-master=https://127.0.0.1:8443 > /tmp/openshift.log 2>&1 &
  SHELL

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "install-all.yml"
    ansible.verbose = "v"
  end
end
